version: '3'
services:
  notifications:
    build: ./notifications
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      spring.datasource.url: "jdbc:mysql://db:3306/notifications?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=notifications
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=db_password